name: Deploy SaaS Monitor PreciosIA

on:
  push:
    branches:
      - dev  # rama que dispara el deploy

env:
  DEPLOY_PATH: /var/www/saas-monitor-preciosIA

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      # 3️⃣ Limpiar conflictos de package.json y package-lock.json
      - name: Resolve package.json conflicts
        run: |
          git checkout --ours package.json || echo "No conflict in package.json"
          git checkout --ours package-lock.json || echo "No conflict in package-lock.json"
          npm install

      # 4️⃣ Verificar conexión SSH con EC2
      - name: Test SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "SSH conexión exitosa"
            whoami

      # 5️⃣ Crear carpeta de despliegue si no existe
      - name: Create deploy folder on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            sudo mkdir -p ${{ env.DEPLOY_PATH }}
            sudo chown -R ${{ secrets.EC2_USERNAME }}:${{ secrets.EC2_USERNAME }} ${{ env.DEPLOY_PATH }}

      # 6️⃣ Copiar archivos al servidor
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ".,!.git,!node_modules"
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1
          overwrite: true

      # 7️⃣ Instalar dependencias y levantar app con PM2
      - name: Configure and run app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            export NVM_DIR="/home/${{ secrets.EC2_USERNAME }}/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            cd ${{ env.DEPLOY_PATH }}
            git pull origin dev
            # Limpiar conflictos antes de instalar
            git checkout --ours package.json || echo "No conflict in package.json"
            git checkout --ours package-lock.json || echo "No conflict in package-lock.json"
            npm install
            pm2 restart index.js || pm2 start index.js --name saas-monitor
